[package]
name = "log4rs-routing-appender"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[features]
mdc-router = ["file", "log-mdc", "serde-value", "regex", "lazy_static"]

file = ["log4rs/file", "serde"]

[dependencies]
antidote = "1.0"
lazy_static = { version = "0.2", optional = true }
log = "0.3"
log-mdc = { version = "0.1", optional = true }
log4rs = { git = "https://github.com/sfackler/log4rs", default_features = false }
lru-cache = "0.1"
regex = { version = "0.1", optional = true }
serde = { version = "0.8", optional = true }
serde-value = { version = "0.3", optional = true }
